service: test-aws-nodejs
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

plugins:
  - serverless-s3-local
  - serverless-offline

custom:
  s3:
    host: localhost
    directory: ~/aws-data

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: thx-bucket

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          method: GET
          path: /
  s3hook:
    handler: handler.s3hook
    events:
      - s3: thx-bucket
        event: s3:*
  hello:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: /hello

